#pragma once
#include "HashTypes.h" // Defines Hash32, BuilderStatus
#include <vector>
#include <cstdint>

namespace ark::compiler::builder {

// Container for the final build output
struct SealedArtifact {
    // The fully assembled, signed Capsule V1 binary.
    std::vector<uint8_t> capsule_bytes;
    
    // Placeholder for future receipt storage (not generated by Builder).
    std::vector<uint8_t> receipt_bytes;
};

class ArtifactSealer {
public:
    // -------------------------------------------------------------------------
    // SEAL ARTIFACT
    // -------------------------------------------------------------------------
    // Assembles the Capsule V1 binary from the build plan components.
    //
    // Contract:
    // 1. Calculates exact size upfront (no patching).
    // 2. Writes Header + Payload TLVs.
    // 3. Signs the range [0..PayloadEnd).
    // 4. Appends the Signature TLV.
    //
    // Returns:
    // - BuilderStatus::Ok on success.
    // - BuilderStatus::InputTooLarge if any TLV exceeds 64KB.
    // - BuilderStatus::CryptoError if key is invalid.
    static BuilderStatus Seal(
        const Hash32& plan_hash,
        const std::vector<uint8_t>& compiler_id, // UTF-8 bytes
        const std::vector<uint8_t>& reqs,        // Raw blob
        const Hash32& symtab_hash,               // Zero if unused
        const std::vector<uint8_t>& private_key, // 64-byte Ed25519 Extended Key
        SealedArtifact& out_artifact
    );
};

} // namespace ark::compiler::builder